### ISSUE TITLE
Search bar issues

### ISSUE THREAD

**Issue by khaledboka** [cartologic/cartoview_basic_viewer#20]
1. Placeholder text of the search bar is a bit confusing
The reason: the map views a specific layer with some features on it, expected to search this mapview, instead it searches the worldwide map areas and places !
Suggestion: Change the placeholder text to "Search Worldwide Map" so that user will expect the search results not related to the current map view

2. Typed "Cairo" in the search bar and it kept viewing search results every 2~3 obviously this behavior because of a slow network

**Comment by hishamkaram** [comment]
fixed
